### ISSUE TITLE
Are you going to publish this data source to Grafana Marketplace?

### ISSUE THREAD

**Issue by mikhail-vl** [ecadlabs/tezos-grafana-datasource#8]
Hello team,

  I came across this data source and would like to know what is your plans for Tezos Data Source?

**Comment by jevonearth** [comment]
Hi @mikhailredis 

Last time we checked, Grafana charges a not-insignificant-fee annual to publish plugins like this to their store. Unlike publishing dashboards which is free.

**Comment by mikhail-vl** [comment]
Hello @jevonearth,

  As Tezos is a public blockchain I was not aware that Grafana Labs charging commercial fee for it.
  The Tezos Data Source is well done and I am looking forward to try.
